###cassandra-cli 建column family相关字段都大写

CREATE KEYSPACE gxsim
with placement_strategy = 'org.apache.cassandra.locator.NetworkTopologyStrategy'
and strategy_options = {'DC1' : 1 , 'DC2' : 1}
AND durable_writes = true;	

create column family t_sim_gameinfo with comparator=UTF8Type
	AND key_validation_class=UTF8Type
	AND default_validation_class = UTF8Type
	and column_metadata=[
		{column_name: gamename, validation_class: UTF8Type},
		{column_name: ltype, validation_class: UTF8Type},
		{column_name: playname, validation_class: UTF8Type},
		{column_name: expireddates, validation_class: LongType},
		{column_name: prizedate, validation_class: UTF8Type}
	]
	with read_repair_chance=0.1
	and dclocal_read_repair_chance=0.5;	
	

########cql3 所有都小写 
CREATE KEYSPACE gxsim
         WITH REPLICATION = {'class':'NetworkTopologyStrategy', 'dc1' : 3, 'dc2' : 2};
         
CREATE KEYSPACE gxsim WITH REPLICATION = {'class':'SimpleStrategy', 'replication_factor' : 1};         

	
CREATE TABLE t_sim_gameinfo (
  key text PRIMARY KEY,
  gamename text,
  ltype text,
  playname text,
  expireddates timestamp,
  prizedate timestamp
 ) WITH COMPACT STORAGE;	
