package com.joyveb.test.cassandra.dao;

import java.util.List;

import com.joyveb.support.cassandra.BaseCassandraDao;
import com.joyveb.test.cassandra.domain.SimGameInfo;

public interface SimGameInfoDAO extends BaseCassandraDao<String, SimGameInfo> {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SIM_GAMEINFO
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	void insert(SimGameInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table T_SIM_GAMEINFO
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	List<SimGameInfo> selectByExample(SimGameInfo example);
	
	SimGameInfo selectByPrimaryKey(String key);
	
	void batchInsert(List<SimGameInfo> list);

}