package com.joyveb.test.cassandra.domain;

import java.util.Date;

import lombok.Data;
import lombok.EqualsAndHashCode;

import com.joyveb.support.cassandra.CassandraPrimaryKey;

@Data
@EqualsAndHashCode(callSuper=false)
public class SimDrawnumber extends CassandraPrimaryKey<String>{
	
	private String playname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.TERMCODE
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private String termcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.BEGINTIME
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Date begintime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.ENDTIME
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Date endtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.STATE
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Integer state;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.BASECODE
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private String basecode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.SPECIALCODE
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private String specialcode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.CREATEDATE
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Date createdate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.SALESTATUS
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Integer salestatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.ACTSELLAMOUNT
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long actsellamount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.VALIDSELLAMOUNT
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long validsellamount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINTOTALAMOUNT
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long wintotalamount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY1
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER1
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY2
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER2
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY3
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER3
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY4
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER4
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY5
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER5
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY6
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney6;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER6
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber6;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY7
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney7;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER7
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber7;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY8
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney8;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER8
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber8;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY9
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney9;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER9
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber9;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINMONEY10
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winmoney10;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_SIM_DRAWNUMBER.WINNUMBER10
	 * 
	 * @mbggenerated Tue Aug 21 10:23:40 CST 2012
	 */
	private Long winnumber10;


}