package com.joyveb.test.cassandra.domain;

import com.joyveb.support.cassandra.CassandraPrimaryKey;

public class SimProperties extends CassandraPrimaryKey<String> {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_PROPERTIES.VALUE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_PROPERTIES.DES
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String des;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_PROPERTIES.VALUE
     *
     * @return the value of T_SIM_PROPERTIES.VALUE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_PROPERTIES.VALUE
     *
     * @param value the value for T_SIM_PROPERTIES.VALUE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_PROPERTIES.DES
     *
     * @return the value of T_SIM_PROPERTIES.DES
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_PROPERTIES.DES
     *
     * @param des the value for T_SIM_PROPERTIES.DES
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setDes(String des) {
        this.des = des;
    }
}