package com.joyveb.test.cassandra.domain;

import java.util.Date;

import com.joyveb.support.cassandra.CassandraPrimaryKey;

public class SimReceiveData extends CassandraPrimaryKey<String> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.ID
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.PLAYNAME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String playname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.LOGICCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String logiccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.CITYCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.SELLTERMCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String selltermcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.VALIDTERMCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String validtermcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.RUNCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String runcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.TICKETCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String ticketcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.SELLDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Date selldatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.BETNUM
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String betnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.SELLWAY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String sellway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.DRAWWAY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String drawway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.CODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.WITHDRAW
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String withdraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.IDCARD
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.MOBILECODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String mobilecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.PHONECARDNO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String phonecardno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.PHONECARDPASSWORD
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String phonecardpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.SELLPERSONID
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String sellpersonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.CHECKCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String checkcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.CREATEDATE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.ISWIN
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Integer iswin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.WINMONEY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Long winmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.WINGRADE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String wingrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.WINBIGFLAG
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Integer winbigflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.ENCASHTERM
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private String encashterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.CASHDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Date cashdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.ENCASHFLAG
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Integer encashflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_SIM_RECEIVE_DATA.ABANDONDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    private Date abandondatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.ID
     *
     * @return the value of T_SIM_RECEIVE_DATA.ID
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.ID
     *
     * @param id the value for T_SIM_RECEIVE_DATA.ID
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.PLAYNAME
     *
     * @return the value of T_SIM_RECEIVE_DATA.PLAYNAME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getPlayname() {
        return playname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.PLAYNAME
     *
     * @param playname the value for T_SIM_RECEIVE_DATA.PLAYNAME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setPlayname(String playname) {
        this.playname = playname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.LOGICCODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.LOGICCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getLogiccode() {
        return logiccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.LOGICCODE
     *
     * @param logiccode the value for T_SIM_RECEIVE_DATA.LOGICCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setLogiccode(String logiccode) {
        this.logiccode = logiccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.CITYCODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.CITYCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.CITYCODE
     *
     * @param citycode the value for T_SIM_RECEIVE_DATA.CITYCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.SELLTERMCODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.SELLTERMCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getSelltermcode() {
        return selltermcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.SELLTERMCODE
     *
     * @param selltermcode the value for T_SIM_RECEIVE_DATA.SELLTERMCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setSelltermcode(String selltermcode) {
        this.selltermcode = selltermcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.VALIDTERMCODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.VALIDTERMCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getValidtermcode() {
        return validtermcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.VALIDTERMCODE
     *
     * @param validtermcode the value for T_SIM_RECEIVE_DATA.VALIDTERMCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setValidtermcode(String validtermcode) {
        this.validtermcode = validtermcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.RUNCODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.RUNCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getRuncode() {
        return runcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.RUNCODE
     *
     * @param runcode the value for T_SIM_RECEIVE_DATA.RUNCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setRuncode(String runcode) {
        this.runcode = runcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.TICKETCODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.TICKETCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getTicketcode() {
        return ticketcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.TICKETCODE
     *
     * @param ticketcode the value for T_SIM_RECEIVE_DATA.TICKETCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setTicketcode(String ticketcode) {
        this.ticketcode = ticketcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.SELLDATETIME
     *
     * @return the value of T_SIM_RECEIVE_DATA.SELLDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Date getSelldatetime() {
        return selldatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.SELLDATETIME
     *
     * @param selldatetime the value for T_SIM_RECEIVE_DATA.SELLDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setSelldatetime(Date selldatetime) {
        this.selldatetime = selldatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.BETNUM
     *
     * @return the value of T_SIM_RECEIVE_DATA.BETNUM
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getBetnum() {
        return betnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.BETNUM
     *
     * @param betnum the value for T_SIM_RECEIVE_DATA.BETNUM
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setBetnum(String betnum) {
        this.betnum = betnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.SELLWAY
     *
     * @return the value of T_SIM_RECEIVE_DATA.SELLWAY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getSellway() {
        return sellway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.SELLWAY
     *
     * @param sellway the value for T_SIM_RECEIVE_DATA.SELLWAY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setSellway(String sellway) {
        this.sellway = sellway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.DRAWWAY
     *
     * @return the value of T_SIM_RECEIVE_DATA.DRAWWAY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getDrawway() {
        return drawway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.DRAWWAY
     *
     * @param drawway the value for T_SIM_RECEIVE_DATA.DRAWWAY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setDrawway(String drawway) {
        this.drawway = drawway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.CODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.CODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.CODE
     *
     * @param code the value for T_SIM_RECEIVE_DATA.CODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.WITHDRAW
     *
     * @return the value of T_SIM_RECEIVE_DATA.WITHDRAW
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getWithdraw() {
        return withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.WITHDRAW
     *
     * @param withdraw the value for T_SIM_RECEIVE_DATA.WITHDRAW
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setWithdraw(String withdraw) {
        this.withdraw = withdraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.IDCARD
     *
     * @return the value of T_SIM_RECEIVE_DATA.IDCARD
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.IDCARD
     *
     * @param idcard the value for T_SIM_RECEIVE_DATA.IDCARD
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.MOBILECODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.MOBILECODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getMobilecode() {
        return mobilecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.MOBILECODE
     *
     * @param mobilecode the value for T_SIM_RECEIVE_DATA.MOBILECODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setMobilecode(String mobilecode) {
        this.mobilecode = mobilecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.PHONECARDNO
     *
     * @return the value of T_SIM_RECEIVE_DATA.PHONECARDNO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getPhonecardno() {
        return phonecardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.PHONECARDNO
     *
     * @param phonecardno the value for T_SIM_RECEIVE_DATA.PHONECARDNO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setPhonecardno(String phonecardno) {
        this.phonecardno = phonecardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.PHONECARDPASSWORD
     *
     * @return the value of T_SIM_RECEIVE_DATA.PHONECARDPASSWORD
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getPhonecardpassword() {
        return phonecardpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.PHONECARDPASSWORD
     *
     * @param phonecardpassword the value for T_SIM_RECEIVE_DATA.PHONECARDPASSWORD
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setPhonecardpassword(String phonecardpassword) {
        this.phonecardpassword = phonecardpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.SELLPERSONID
     *
     * @return the value of T_SIM_RECEIVE_DATA.SELLPERSONID
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getSellpersonid() {
        return sellpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.SELLPERSONID
     *
     * @param sellpersonid the value for T_SIM_RECEIVE_DATA.SELLPERSONID
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setSellpersonid(String sellpersonid) {
        this.sellpersonid = sellpersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.CHECKCODE
     *
     * @return the value of T_SIM_RECEIVE_DATA.CHECKCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getCheckcode() {
        return checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.CHECKCODE
     *
     * @param checkcode the value for T_SIM_RECEIVE_DATA.CHECKCODE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setCheckcode(String checkcode) {
        this.checkcode = checkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.CREATEDATE
     *
     * @return the value of T_SIM_RECEIVE_DATA.CREATEDATE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.CREATEDATE
     *
     * @param createdate the value for T_SIM_RECEIVE_DATA.CREATEDATE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.ISWIN
     *
     * @return the value of T_SIM_RECEIVE_DATA.ISWIN
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Integer getIswin() {
        return iswin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.ISWIN
     *
     * @param iswin the value for T_SIM_RECEIVE_DATA.ISWIN
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setIswin(Integer iswin) {
        this.iswin = iswin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.WINMONEY
     *
     * @return the value of T_SIM_RECEIVE_DATA.WINMONEY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Long getWinmoney() {
        return winmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.WINMONEY
     *
     * @param winmoney the value for T_SIM_RECEIVE_DATA.WINMONEY
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setWinmoney(Long winmoney) {
        this.winmoney = winmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.WINGRADE
     *
     * @return the value of T_SIM_RECEIVE_DATA.WINGRADE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getWingrade() {
        return wingrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.WINGRADE
     *
     * @param wingrade the value for T_SIM_RECEIVE_DATA.WINGRADE
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setWingrade(String wingrade) {
        this.wingrade = wingrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.WINBIGFLAG
     *
     * @return the value of T_SIM_RECEIVE_DATA.WINBIGFLAG
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Integer getWinbigflag() {
        return winbigflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.WINBIGFLAG
     *
     * @param winbigflag the value for T_SIM_RECEIVE_DATA.WINBIGFLAG
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setWinbigflag(Integer winbigflag) {
        this.winbigflag = winbigflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.ENCASHTERM
     *
     * @return the value of T_SIM_RECEIVE_DATA.ENCASHTERM
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public String getEncashterm() {
        return encashterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.ENCASHTERM
     *
     * @param encashterm the value for T_SIM_RECEIVE_DATA.ENCASHTERM
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setEncashterm(String encashterm) {
        this.encashterm = encashterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.CASHDATETIME
     *
     * @return the value of T_SIM_RECEIVE_DATA.CASHDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Date getCashdatetime() {
        return cashdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.CASHDATETIME
     *
     * @param cashdatetime the value for T_SIM_RECEIVE_DATA.CASHDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setCashdatetime(Date cashdatetime) {
        this.cashdatetime = cashdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.ENCASHFLAG
     *
     * @return the value of T_SIM_RECEIVE_DATA.ENCASHFLAG
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Integer getEncashflag() {
        return encashflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.ENCASHFLAG
     *
     * @param encashflag the value for T_SIM_RECEIVE_DATA.ENCASHFLAG
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setEncashflag(Integer encashflag) {
        this.encashflag = encashflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_SIM_RECEIVE_DATA.ABANDONDATETIME
     *
     * @return the value of T_SIM_RECEIVE_DATA.ABANDONDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public Date getAbandondatetime() {
        return abandondatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_SIM_RECEIVE_DATA.ABANDONDATETIME
     *
     * @param abandondatetime the value for T_SIM_RECEIVE_DATA.ABANDONDATETIME
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void setAbandondatetime(Date abandondatetime) {
        this.abandondatetime = abandondatetime;
    }
}