package com.joyveb.test.cassandra.dao.impl;

import java.util.List;

import me.prettyprint.cassandra.serializers.StringSerializer;
import me.prettyprint.cassandra.utils.Assert;
import me.prettyprint.hector.api.Keyspace;

import com.joyveb.support.cassandra.CassandraDaoSupport;
import com.joyveb.test.cassandra.dao.SimGameInfoDAO;
import com.joyveb.test.cassandra.domain.SimGameInfo;

public class SimGameInfoDAOImpl extends CassandraDaoSupport<String, SimGameInfo> implements SimGameInfoDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SIM_GAMEINFO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public SimGameInfoDAOImpl(Keyspace keyspace, String columnFamilyName) {
        super(keyspace, columnFamilyName, StringSerializer.get());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SIM_GAMEINFO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public void insert(SimGameInfo record) {
//    	Mutator<String> mutator = HFactory.createMutator(this.keyspace, stringSerializer);
//		String key = record.getLtype();
//		mutator.addInsertion(key, columnFamilyName, HFactory.createStringColumn("GAMENAME", record.getGamename()))
//        	.addInsertion(key, columnFamilyName, HFactory.createStringColumn("LTYPE", record.getLtype()))
//            .addInsertion(key, columnFamilyName, HFactory.createStringColumn("PLAYNAME", record.getPlayname()))
//            .addInsertion(key, columnFamilyName, HFactory.createColumn("EXPIREDDATES", record.getExpireddates(), stringSerializer, IntegerSerializer.get()))
//            .addInsertion(key, columnFamilyName, HFactory.createStringColumn("PRIZEDATE", record.getPrizedate()));
//        getCFTemplate().executeBatch(mutator);
    	//record.setKey(record.getPlayname());
    	super.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_SIM_GAMEINFO
     *
     * @mbggenerated Tue Aug 21 10:23:40 CST 2012
     */
    public List<SimGameInfo> selectByExample(SimGameInfo example) {
    	String cql = "select * from " + columnFamilyName;
    	return selectByCQL(cql);
//    	return super.selectByExample(example);
    }

	@Override
	protected SimGameInfo createPOJO() {
		return new SimGameInfo();
	}

	protected boolean validateKey(SimGameInfo t) {
		Assert.notNull(t, "bean is null.");
		Assert.notNull(t.getPlayname(), "playname is null.");
		return true;
	}

}